### PR TITLE
add 2 functions

### PR DESCRIPTION
**Pull request by telppa**
Gdip_DrawRoundedRectanglePath() and Gdip_FillRoundedRectanglePath() can be drawn better rounded rectangle.

by just me.

### CODE REVIEW

**Comment by marius-sucan** [comment]
I'd like to commit this pull request, but the functions use direct DLL calls for GDI+ functions that are already implemented.

I would like to have instead these DLL calls, the actual ahk functions. Is that okay with you?

Thank you. 

Best regards, Marius.

**Comment by telppa** [comment]
The 2 functions were written by just me, and I just collected them. If you ask my opinion, i am ok.

**Comment by marius-sucan** [comment]
I'll add these two functions, but I'll modify them as I suggested.

I'll release an updated file hopefully today or tomorrow.

The new version will bring support for arrays in many functions, in addition to strings like "value1|value2|value3".

Best regards, Marius.

**Comment by marius-sucan** [comment]
The new version was pushed to the repository. I modularized the functions and tested them through Quick Picto Viewer .

**Pull request closed without merging**
