### PR TITLE
Added 3 functions

### PR DESCRIPTION
**Pull request by telppa**

### CODE REVIEW

**Review by marius-sucan — COMMENTED** [review]
Please tell me what prompts these three new functions?

Gdip_ApplySpecialFixedBlur() is made by me, taken from the main QPV source file.

Best regards, Marius.

**Comment by telppa** [comment]
Gdip_DrawRoundedRectanglePath() and Gdip_FillRoundedRectanglePath() can be drawn better rounded rectangle. 

Gdip_ApplySpecialFixedBlur() can be implemented blurring, pixelation and many other effects.

I noticed this gdip libraries are newer than other place (AHK-GDIp-Library-Compilation), so i push requests here.

Also since Gdip_ApplySpecialFixedBlur() is your function.

I didn't write your name, because I noticed that the functions you add in gdip library usually don't have your name added.

**Comment by marius-sucan** [comment]
I will release a new version of the gdiplus compilation library, soonish. 

Yes, QPV has always the newest version of it.

The blur function will never be included in the compilation library. Its purpose is very "specialized" for QPV. It is meant to help counteract the poor quality of gdiplus blur at small radius.

Best regards, Marius.

**Comment by telppa** [comment]
I'm a little confused, I tested and found that 
Gdip_BoxBlurBitmap() 
Gdip_BlurBitmap() 
Gdip_ApplySpecialFixedBlur() 
The blur effect are three completely different effects.

The effect created by Gdip_ApplySpecialFixedBlur is very much like Gaussian blur, which is one of the most popular used blur effects, so why can't it be added to the gdip library?

**Comment by telppa** [comment]
I guess you mean that they won't be added to qpv's gdip library, but can be added to AHK-GDIp-Library-Compilation ?

**Comment by marius-sucan** [comment]
Gdip_BoxBlurBitmap() and Gdip_BlurBitmap() are already present in the AHK-GDIp-Library-Compilation.

 BoxBlur uses an mcode [c++ code] that yields ugly results in most cases.

BlurBitmap() relies on downscaling and upscaling an image with GDI+ DrawImage.

Gdip_ApplySpecialFixedBlur() will not be integrated into AHK-GDIp-Library-Compilation because it is meant for Quick Picto Viewer . I will add a similar one into the library.

Gdip_ApplySpecialFixedBlur() relies on internal GDI+ algorithms for blurring and is the best. It uses Gdip_CreateEffect() function. You can use CreateEffect() as well .

Best regards, Marius.

**Pull request closed without merging**
